# Generated by Django 4.1.7 on 2023-02-16 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('headline', models.TextField()),
                ('intro', models.TextField()),
                ('description', models.TextField()),
                ('product_label', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.TextField()),
                ('product_affiliate_url', models.CharField(max_length=250)),
                ('faq_answer_1', models.TextField()),
                ('faq_answer_2', models.TextField()),
                ('faq_answer_3', models.TextField()),
                ('faq_question_1', models.TextField()),
                ('faq_question_2', models.TextField()),
                ('faq_question_3', models.TextField()),
                ('product_image_url', models.CharField(max_length=250)),
                ('product_image_alt', models.CharField(max_length=250)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subcategory')),
            ],
        ),
    ]
