# Generated by Django 4.1.7 on 2023-02-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='reviewpost',
            table='review_post',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_category',
        ),
    ]
