# Generated by Django 4.1.7 on 2023-03-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_table_alter_reviewpost_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_url', models.CharField(db_index=True, max_length=250, unique=True)),
                ('product_price', models.CharField(max_length=250)),
                ('product_reviews', models.CharField(max_length=250)),
                ('product_ratings', models.CharField(max_length=250)),
                ('product_image', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='product_affiliate_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.product', to_field='affiliate_url'),
        ),
    ]
