# Generated by Django 4.1.7 on 2023-04-18 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_group_product_category_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewpost',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='product_image_alt',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='product_image_url',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='product_label',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_alt',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='product_label',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ratings',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_reviews',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='product_affiliate_url',
            field=models.ForeignKey(db_column='product_affiliate_url', on_delete=django.db.models.deletion.CASCADE, to='blog.product', to_field='affiliate_url'),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
