version: '3.7'

services:
  postgres:
    build: ./postgres
    restart: always
    env_file:
      - ./server/.env
    image: iamdavidmiguelalvarez/review_poster:postgres
    volumes:
    - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: