version: '3.7'

services:
  cms:
    build: ./cms/server
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    image: iamdavidmiguelalvarez/review_poster/cms
    ports:
    - "4008:4008"
  postgres:
    build: ./postgres
    restart: always
    env_file:
      - .env
    image: iamdavidmiguelalvarez/review_poster:postgres
    volumes:
    - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: