version: '3.7'

services:
  server:
    build: ./server
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    image: iamdavidmiguelalvarez/review_poster:server
    ports:
    - "4009:4009"
  django:
    build: ./django
    restart: always
    depends_on:
      - postgres
    image: iamdavidmiguelalvarez/review_poster:django
    env_file:
      - ./server/.env
    volumes:
    - data:/vol/django
    ports:
      - "8000:8000"
  postgres:
    build: ./postgres
    restart: always
    env_file:
      - ./server/.env
    image: iamdavidmiguelalvarez/review_poster:postgres
    volumes:
    - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: